# Generated by Django 3.0.2 on 2020-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posts',
            constraint=models.UniqueConstraint(fields=('Post_location',), name='unique_location'),
        ),
    ]
